### ISSUE TITLE
All campaigns loading issue

### ISSUE THREAD

**Issue by guerrap** [carrot-kpi/v1-monorepo#223]
On the campaigns page, when the loading is completed there's an issue that causes the `<Empty />` component to be rendered for a second, before showing the actual campaigns.

This is probably caused by the `useDebounce` inside the `useSearchedResolvedKPITokens`, and how that hook is Implemented.

https://user-images.githubusercontent.com/9011637/230117599-f14e7ad6-7b08-4fda-bfd5-00cc86f3f807.mp4

**Comment by Diogomartf** [comment]
I can look into this.

**Comment by Diogomartf** [comment]
these are some the logs for the loading and data.

first data comes empty and loading true: `loading=true; data=[]`

<img width="363" alt="image" src="https://user-images.githubusercontent.com/5664434/232755505-eb6218f9-2692-413b-b732-b8730e21ad8f.png">

The problem seems to be after that the loading is false and data comes empty.

`loading=false; data=[]` is the condition to show the empty state.


<img width="325" alt="image" src="https://user-images.githubusercontent.com/5664434/232755550-4d608714-6ce3-456f-9387-6b6872ce5443.png">

At the end the data comes and it shows the cards.

**Comment by Diogomartf** [comment]
it's related with the debounce we have on `useSearchedResolvedKPITokens`, it's messing with the timing of setting `loading=false`
